'use strict'

/*
 * DARKNOTE L2 — YouTube downloader entry point.
 *
 * The implementation lives in ytdl.source.js. This file loads the obfuscated
 * build (ytdl.protected.js, generated by `npm run protect`) when it is present
 * and falls back to the readable source otherwise.
 *
 * Why a shim: BIGBRO.js and lib/shazam.js (and anything added later) already
 * require('./ytdl.js'), so routing them through here means the protected build
 * is used everywhere without editing a single consumer.
 *
 * Note lib/shazam.js is itself protected, so its own require('./ytdl.js') string
 * is obfuscated too — keeping that path stable is deliberate.
 */

let implementation
try {
    implementation = require('./ytdl.protected.js')
} catch (error) {
    const missing = error?.code === 'MODULE_NOT_FOUND' && String(error.message || '').includes('ytdl.protected')
    if (!missing) {
        // The file exists but is broken: say so loudly instead of hiding it.
        console.error('[PROTECT] ytdl.protected.js failed to load — falling back to the readable source:', error?.stack || error)
    }
    implementation = require('./ytdl.source.js')
}

module.exports = implementation
